<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="index.aspx.cs" Inherits="Trendyol.UI.index" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="Assets/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:Button ID="btnProductsAdd" runat="server" Text="Veritabanına Ürünleri Doldur" OnClick="btnProductsAdd_Click"/>
            <table>
                <thead>
                    <tr>
                        <th>Ürünler</th>
                        <th>Sepete Eklenen Ürünler</th>
                        <th>Tanımlanan Siparişler</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <asp:GridView ID="grdProducts" DataKeyNames="ProductID" runat="server" CellPadding="4" ForeColor="Black" GridLines="Vertical" Width="497px" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" AutoGenerateColumns="False" AutoGenerateSelectButton="True" OnSelectedIndexChanged="ProductAdd">
                                <AlternatingRowStyle BackColor="White" />
                                <Columns>
                                    <asp:BoundField DataField="ProductName" HeaderText="Ürün Adı" />
                                    <asp:BoundField DataField="UnitPrice" HeaderText="Ürün Fiyatı" />
                                    <asp:BoundField DataField="UnitsInStock" HeaderText="Stok Miktarı" />
                                </Columns>
                                <FooterStyle BackColor="#CCCC99" />
                                <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                                <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                                <RowStyle BackColor="#F7F7DE" />
                                <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                                <SortedAscendingCellStyle BackColor="#FBFBF2" />
                                <SortedAscendingHeaderStyle BackColor="#848384" />
                                <SortedDescendingCellStyle BackColor="#EAEAD3" />
                                <SortedDescendingHeaderStyle BackColor="#575357" />
                            </asp:GridView>
                        </td>
                        <td>
                            <asp:GridView ID="grdOrderProducts" DataKeyNames="ProductID" runat="server" CellPadding="4" ForeColor="Black" GridLines="Vertical" Width="497px" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" OnRowDeleting="grdOrderProducts_RowDeleting">
                                <AlternatingRowStyle BackColor="White" />
                                <Columns>
                                    <asp:BoundField DataField="ProductName" HeaderText="Ürün Adı" />
                                    <asp:BoundField DataField="Quantity" HeaderText="Miktar" />
                                    <asp:BoundField DataField="UnitPrice" HeaderText="Ürün Fiyatı" />
                                    <asp:BoundField DataField="Store" HeaderText="Depo" />
                                </Columns>
                                <FooterStyle BackColor="#CCCC99" />
                                <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                                <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                                <RowStyle BackColor="#F7F7DE" />
                                <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                                <SortedAscendingCellStyle BackColor="#FBFBF2" />
                                <SortedAscendingHeaderStyle BackColor="#848384" />
                                <SortedDescendingCellStyle BackColor="#EAEAD3" />
                                <SortedDescendingHeaderStyle BackColor="#575357" />
                            </asp:GridView>
                        </td>

                    </tr>
                    <tr>
                        <td>
                            <asp:GridView ID="grdOrders" runat="server" CellPadding="4" ForeColor="Black" GridLines="Vertical" Width="497px" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" AutoGenerateColumns="False">
                                <AlternatingRowStyle BackColor="White" />
                                <Columns>
                                    <asp:BoundField DataField="OrderID" HeaderText="Ürün Adı" />
                                    <asp:BoundField DataField="Operating" HeaderText="İşlem Yapılıyor" />
                                    <asp:BoundField DataField="EndOrder" HeaderText="Sonlandırıldı" />
                                </Columns>
                                <FooterStyle BackColor="#CCCC99" />
                                <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                                <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                                <RowStyle BackColor="#F7F7DE" />
                                <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                                <SortedAscendingCellStyle BackColor="#FBFBF2" />
                                <SortedAscendingHeaderStyle BackColor="#848384" />
                                <SortedDescendingCellStyle BackColor="#EAEAD3" />
                                <SortedDescendingHeaderStyle BackColor="#575357" />
                            </asp:GridView>
                        </td>
                    </tr>
                </tbody>


            </table>
            <asp:Button ID="btnOrderAdd" runat="server" OnClick="btnOrderAdd_Click" Text="Depoya Aktar" />
            <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>
        </div>
    </form>
</body>
</html>
